name: Tagged Release

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - '**/LICENSE'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1

      - name: Nuget Restore
        run: nuget restore

      - name: Build .Net8
        run: msbuild /t:AssetStudio_GUI:publish /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Build .Net8 CLI
        run: msbuild /t:AssetStudio_CLI:publish /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Create release zip
        run: tar -C AssetStudio.GUI/bin/Release/net8.0-windows/publish -a -cvf net8.0-windows.zip *

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: net8.0-windows.zip

    
